workflows:
    android-workflow-id:
        name: Android Sample Workflow
        triggering:
          events:
            - push
            - tag
            - pull_request
        artifacts:
          - android/app/build/outputs/**/*.apk
        publishing:
          email:
            recipients:
              - m.gikas@doubleip.com
            notify:
              success: true
              failure: false  
    ios-workflow-id:
        name: iOS Sample Workflow