workflows:
    android-workflow-id:
        name: Android Sample Workflow
        # .......    
        # .......
        # .......  
    ios-workflow-id:
        name: iOS Sample Workflow
        artifacts:
          - android/app/build/outputs/**/*.apk
        publishing:
        email:
          recipients:
            - m.gikas@doubleip.com
          notify:
            success: true
            failure: false